### ISSUE TITLE
How to set global template values? Trying to add via RenderableTemplate doesn't work

### ISSUE THREAD

**Issue by limist** [yogthos/Selmer#73] opened 2015-02-02 19:23 UTC
It's sometimes very useful to have some values as always/globally available when rendering Selmer templates.  AFAICT, there's one clear way to do that - by injecting keys and values in the `RenderableTemplate` type definition.  Another way is modifying a `render` function used site-wide - but the limitation there is, one cannot use information only available at runtime, like the locale.  

For example, when Selmer is used with Luminus, there's a site-specific render function in the `myproject.layout` namespace that looks like,

```clojure
(ns tryluminus.layout
  (:require [selmer.parser :as parser]
            [clojure.string :as s]
            [ring.util.response :refer [content-type response]]
            [compojure.response :refer [Renderable]]
            [environ.core :refer [env]]
            [noir.session :as session]))

(parser/set-resource-path! (clojure.java.io/resource "templates"))

(deftype
  RenderableTemplate
  [template params]
  Renderable
  (render
    [this request]
    (content-type
      (->>
        (assoc params
                   (keyword (s/replace template #".html" "-selected")) "active"
                  :dev (env :dev)
                  :servlet-context (if-let [context (:servlet-context request)]
                                             (try
                                                   (.getContextPath context)
                                                   (catch IllegalArgumentException _ context)))
                  :foo1 "bar"
                  :foo2 (get-some-runtime-value)
                  :user-id (session/get :user-id))
        (parser/render-file (str template))
        response)
      "text/html; charset=utf-8")))

(defn render [template & [params]]
  (RenderableTemplate. template params))
```

In the above code, I want to add more k/v pairs like the `:foo1` or `:foo2` keys, but when referenced in other templates via `{{foo1}}` nothing shows up; whereas `{{user-id}}` or `{{dev}}` work fine. How can that be??  Reloading the page, to reloading the JVM process, doesn't help.  And if some k/v like `foo2` requiring runtime information is put into the `render` function, that causes compilation errors.

So, what is the right way to have custom global (throughout a project anyway) values in Selmer templates?  Thanks.

**Comment by yogthos** [comment] 2015-02-02 22:54
There's nothing Selmer specific here that I can see. The way you're populating keys in params is perfectly fine. For example, if you have:

```clojure
(def global (atom "foo bar"))

(deftype RenderableTemplate [template params]
  Renderable
  (render [this request]
    (content-type
      (->> (assoc params
                  (keyword (s/replace template #".html" "-selected")) "active"
                  :foo1 "bar"
                  :foo2 @global ;;referencing a global variable
                  :dev (env :dev)
                  :servlet-context
                  (if-let [context (:servlet-context request)]
                    ;; If we're not inside a serlvet environment (for
                    ;; example when using mock requests), then
                    ;; .getContextPath might not exist
                    (try (.getContextPath context)
                         (catch IllegalArgumentException _ context))))
        (parser/render-file (str template))
        response)
      "text/html; charset=utf-8")))
```

Above, both `:foo1` and `:foo2` render when referenced using `{{foo1}}` and `{{foo2}}` as expected. Perhaps the issue is with how you're calling the `get-some-runtime-value` in your case. I certainly can't see any reason why `:foo1` wouldn't render for you though.

**Comment by limist** [comment] 2015-02-02 23:14
Thanks for the feedback, and sanity check. :)  Something like the `:foo1 "bar"` k/v pair should work, but it's not.  In my base template I'm sticking in `{{dev}} {{foo1}}` and the first shows up `true` as expected, while there's nothing for the `foo1` value.  

I'm stumped or ideas; any suggestions as to a debugging strategy?  Thanks again.

**Comment by yogthos** [comment] 2015-02-02 23:26
I tried an example locally with the code I pasted above and I can't reproduce the problem myself. Is your `:foo1` pointing to a string as in your example or a different value?

**Comment by limist** [comment] 2015-02-02 23:34
It's just a plain string, `:foo "bar"`  Seemingly too simple to not work.  Any way to fiddle the `deftype` to debug?

**Comment by yogthos** [comment] 2015-02-02 23:52
I'm really not sure what's happening in your case, but it really doesn't appear to have anything to do with selmer specifically as it simply gets a map that's passed to it and renders keys from it. As long as you don't have a typo or something it really should work fine.

There is absolutely no difference where you define the context map and deftype shouldn't have any effect on it. You could try rendering this from the `render` function directly as well.

**Comment by yogthos** [comment] 2015-02-03 04:53
I'm going to close the issue, I'm not able to reproduce this and it does not appear to be related to Selmer itself. As I explained, it doesn't matter how the context map is populated from Selmer perspective, as long as the variable is present and referenced by the same name in the template it will be rendered.

**Closed by yogthos** 2015-02-03 04:53 UTC

**Comment by limist** [comment] 2015-02-03 13:09
OK, thanks again for your help and sanity-checking.  FWIW, I swept though all dependencies in my project to update them, then blew away the local `.m2` repository and local builds.  After re-building, things work. :)
