### ISSUE TITLE
Can't find template file in depended jar file when parser/set-resource-path! used

### ISSUE THREAD

**Issue by tendant** [yogthos/Selmer#176] opened 2018-07-26 21:19 UTC
Looks like set-resource-path! doesn't play nice with template in classpath from jar file. 

I have created testing project for this issue. 

A child project https://github.com/tendant/selmer-test-child, which will be built as a jar library. It works all the time. 

A parent project https://github.com/tendant/seller-test-parent, which will include child project as dependency and call function in child project to render template. 

When parser/set-resource-path! is used, parent project can't find resource packaged in child project. When  parser/set-resource-path! is NOT used, parent project works fine.

**Comment by yogthos** [comment] 2018-07-27 12:19
The problem is that you're calling `parser/set-resource-path!` with `(io/resource "templates"))`, and  `set-resource-path!` processes the argument using the [make-resource-path](https://github.com/yogthos/Selmer/blob/267c6993994e6f163a2a36b679d06bc2bf03e23b/src/selmer/parser.clj#L46) function that will call `str` on it. So, `(io/resource "templates")` will be turned into `"file:/path/to/project/resources/templates"`, and that's why it's not being found in the jar.

**Comment by tendant** [comment] 2018-07-27 17:16
If use string directly, instead of io/resource. The child project won't be able to find template with below error:

Sample code in commit: https://github.com/tendant/selmer-test-child/commit/0af1423afce22639bff60516e157a48dcb3ffbce

Caused by: java.io.FileNotFoundException: /templates/demo.html (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at clojure.java.io$fn__10972.invokeStatic(io.clj:238)
        at clojure.java.io$fn__10972.invoke(io.clj:235)
        at clojure.java.io$fn__10881$G__10874__10888.invoke(io.clj:69)
        at clojure.java.io$fn__10942.invokeStatic(io.clj:165)
        at clojure.java.io$fn__10942.invoke(io.clj:165)
        at clojure.java.io$fn__10894$G__10870__10901.invoke(io.clj:69)
        at clojure.java.io$reader.invokeStatic(io.clj:102)
        at clojure.java.io$reader.doInvoke(io.clj:86)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at selmer.validator$validate_tags.invokeStatic(validator.clj:103)
        at selmer.validator$validate_tags.invoke(validator.clj:102)
        at selmer.validator$validate.invokeStatic(validator.clj:116)
        at selmer.validator$validate.invoke(validator.clj:113)
        at selmer.template_parser$read_template.invokeStatic(template_parser.clj:197)
        at selmer.template_parser$read_template.invoke(template_parser.clj:191)
        at selmer.template_parser$preprocess_template.invokeStatic(template_parser.clj:253)
        at selmer.template_parser$preprocess_template.doInvoke(template_parser.clj:252)

**Comment by yogthos** [comment] 2018-07-27 18:04
You could try constructing the URL as follows:

```clojure
(.nextElement (ClassLoader/getSystemResources "templates"))
```

**Comment by tendant** [comment] 2018-07-27 19:14
Then it back to original problem, which works for child project, and doesn't work for parent project. 

File couldn't be found in parent project.

**Comment by yogthos** [comment] 2018-07-28 00:33
Are you able to load the file via the resource path outside selmer?

It seems that if the file is accessible via the URL object, then selmer should be able to read it.

**Comment by yogthos** [comment] 2018-07-31 21:08
I won't have time to look at this in the near future, but it sounds like the `make-resource-path` function might need to be more flexible. If you can take a look at a PR I could help with that in the meantime.

**Comment by yogthos** [comment] 2019-09-09 18:18
should be fixed with https://github.com/yogthos/Selmer/pull/207

**Closed by yogthos** 2019-09-09 18:18 UTC
Labels: help wanted
