### ISSUE TITLE
Selmer doenst work on windows

### ISSUE THREAD

**Issue by chiniara** [yogthos/Selmer#215] opened 2020-02-18 20:52 UTC
Hi, 
I was trying to use Cryogen to make a blog but i started getting errors when building.
After some investigations i found that the problem was not in Cryogen but in Selmer.
It appears that this commit : https://github.com/yogthos/Selmer/commit/1acae051f3d693c98c44b64fead0dc13d7f01a93 , broke windows compatibility.

This is the error
`Error: resource-path for /html/page.html returned nil, typically means the file doesn't exist in your classpath. `

I tried to fix it but with no success as im still a clojure beginner.
I could try to fix it again with some guidance though.
Thank you

**Comment by yogthos** [comment] 2020-02-19 16:31
Hi,

It looks like the path is being represented differently on windows. I don't have windows handy myself, but an easy thing to try would be to add some `println`s in the functions resolving the path to see what it looks like. It likely has `\` slashes instead of `/`.

It might just be a matter of changing `(.startsWith f "/") (.toURL (io/file f))` calls to `(.startsWith f java.io.File/separator) (.toURL (io/file f))`.

**Comment by chiniara** [comment] 2020-02-19 19:36
I'll try to do some more debugging when i get home and also will try this : 

> It might just be a matter of changing (.startsWith f "/") (.toURL (io/file f)) calls to (.startsWith f java.io.File/separator) (.toURL (io/file f)).

Will report later

**Comment by chiniara** [comment] 2020-02-20 01:30
Yeah i tried to debug and fix it but i wasnt able, this is the kind of path that is forming:
![image](https://user-images.githubusercontent.com/6012227/74892040-44d88980-5367-11ea-89e4-a16ab7f9aa21.png)
I get the same error
`Error: resource-path for /html/page.html returned nil, typically means the file doesn't exist in your classpath.`

**Comment by yogthos** [comment] 2020-02-20 04:28
Are you passing `"/html/page.html"` as the input path for the template? Have you tried changing that to `"html\page.html` instead. The `D:\Dev\Projects\clojure\my-log\themes\blue//html/page.html` looks like it would be invalid.

**Comment by chiniara** [comment] 2020-02-20 05:43
After some more fiddling i started passing some "valid" paths.
I say valid because windows can understand them, but im still getting errors

![image](https://user-images.githubusercontent.com/6012227/74904392-96ded680-538a-11ea-9ad0-330e0ed9ab5a.png)

I also changed cryogen to use the `java.io.File/separator`, the paths are now using `\` but i still get the error
![image](https://user-images.githubusercontent.com/6012227/74904539-c261c100-538a-11ea-82e9-159f06cbbd16.png)

**Comment by yogthos** [comment] 2020-02-20 21:10
The path still doesn't look right since you've got `...blue/html...` in there.

**Comment by chiniara** [comment] 2020-02-21 02:04
I found the place where it was putting the `/`
But its not that still
![image](https://user-images.githubusercontent.com/6012227/74997619-41abcf00-5435-11ea-9825-c72c35b129d2.png)

its something else....

**Comment by yogthos** [comment] 2020-02-21 02:13
Yeah, so it looks like the `resource-path` function isn't resolving the path correctly. Based on the error message it looks like the function is getting `html\page.html` as the input string for the path. I'm assuming that's relative to the `resources` folder in the project.

 I would recommend playing around with the `resource-path` independently in the REPL to see if you can get it to resolve the resource path that way. Then we can take a look at what changes would be required.

**Comment by chiniara** [comment] 2020-02-21 02:37
Yes, im still investigating but i missed some prints 
Here its setting the resource paths correctly it seems
![image](https://user-images.githubusercontent.com/6012227/74998799-75d4bf00-5438-11ea-9f9d-61311ac5fd41.png)

But on the resource-path function this is happening
![image](https://user-images.githubusercontent.com/6012227/74999234-dd3f3e80-5439-11ea-837c-96914e9c9820.png)

And its falling here but i don't understand this function

![image](https://user-images.githubusercontent.com/6012227/74999252-e7f9d380-5439-11ea-908d-9d8fd2a69d27.png)

I think that the problem is in here OR in the resource-path conditions

**Comment by yogthos** [comment] 2020-02-24 00:14
Basically, the code is loading the resource by looking up the resource path from the current thread. So, I think the issue here is that the string path is being used directly in the fall through case, but in the original version before the change it would always be converted to a URL. As a test, try changing `:else (io/resource f)` to `:else (io/resource (java.net.URL. f))`. If that fixes it, then it's a matter of matching the pattern for windows style file path.

**Comment by chiniara** [comment] 2020-02-24 17:35
Hey i tried using the java.net.URL directly but i kept getting this error 
![image](https://user-images.githubusercontent.com/6012227/75176370-d1da6480-5712-11ea-9b62-1f252719aee3.png)
I did some research and found that this error was because it was missing the file protocol, so i added it and :
![image](https://user-images.githubusercontent.com/6012227/75176422-e880bb80-5712-11ea-93b8-a4e69feb7620.png)
It found the file! now i don't know why it isnt adding the protocol to the file

**Comment by yogthos** [comment] 2020-02-24 22:31
Hmm, not sure how `file:///` was being added previously since it wasn't being done in Selmer before the change either.

**Comment by cpmcdaniel** [comment] 2020-03-30 04:25
I have discovered the root cause of this issue. It all boils down to java.io.File#getAbsolutePath returning a fully-qualified Windows path like `C:\foo\blah`. If you pass that into `set-resource-path`, it isn't recognized as fully-qualified because it is looking for "/" or "file:/" at the start of the string. It simply gets "/" appended to the end. So my example becomes `C:\foo\blah/`. 

Some moments later... `selmer.util/resource-path` gets called to resolve a template (or include). Again, it is looking for a string that starts with "/", "file:/", or "jar:file:/". Ours doesn't start with any of those, so it hits the :else of the cond and `(io/resource f)` returns nil if it can't find f on the classpath. 

I do not think the solution is to try to match Windows-style file name patterns. I think the right solution is to not call `getAbsolutePath` but call `getAbsoluteFile` instead and convert that to a `java.net.URL`. This would mean the bug fix is actually in cryogen. However, I see the same mistake in the Selmer unit tests, and indeed, they fail on Windows. PR incoming...

**Comment by cpmcdaniel** [comment] 2020-03-30 04:35
I didn't quite successfully link the PR to this issue. You can go ahead and close this. I'm going to submit a PR to cryogen-core as well to fix the root cause of the issue there.

**Comment by yogthos** [comment] 2020-03-30 14:34
Perfect, thanks for digging in and getting the PR up.

**Closed by yogthos** 2020-03-30 14:34 UTC

**Comment by chiniara** [comment] 2020-03-30 14:41
Thank you very much! 
I wasnt able to investigate anymore, sadly.
