### ISSUE TITLE
Problem with currency-format

### ISSUE THREAD

**Issue by dmcollie** [yogthos/Selmer#74] opened 2015-02-28 17:36 UTC
Using Selmer 0.8.0 I have this in the page template:

<td>{{school.annual-tuition-fees|currency-format:en:GB}}</td>

but it produces the following error:

28 Feb 2015 17:34:03 ERROR middleware - #<Exception java.lang.Exception: On filter body 'school.annual-tuition-fees|currency-format:en:GB' and filter 'currency-format:en:GB' this error occurred:Wrong number of args (3) passed to: filters/fn--1120/fn--1139>

I had expected that passing the :en:GB args to the filter would work.

**Comment by yogthos** [comment] 2015-02-28 18:24
I'm not able to reproduce the issue with Selmer:

```clojure
(render "{{school.annual-tuition-fees|currency-format:en:GB}}" {:school {:annual-tuition-fees 100.4}})
=>"£100.40"
```

It's possible there some other problem with the middleware or your template, the error does not appear to be Selmer specific either.

**Comment by yogthos** [comment] 2015-03-01 21:15
Closing the issue as I can't reproduce it and it doesn't appear to be Selmer specific.

**Closed by yogthos** 2015-03-01 21:15 UTC
